ista::owl2::AnonymousIndividual
std::string ista::owl2::AnonymousIndividual::node_id_
ista::owl2::AnonymousIndividual::AnonymousIndividual(const std::string &node_id)
Referenced by operator!=, operator<, operator==.
std::string ista::owl2::AnonymousIndividual::getNodeID() const
Referenced by std::hash< ista::owl2::AnonymousIndividual >::operator().
bool ista::owl2::AnonymousIndividual::operator==(const AnonymousIndividual &other) const
References AnonymousIndividual.
bool ista::owl2::AnonymousIndividual::operator!=(const AnonymousIndividual &other) const
References AnonymousIndividual.
bool ista::owl2::AnonymousIndividual::operator<(const AnonymousIndividual &other) const
References AnonymousIndividual.