ista::owl2::Axiom
std::vector<Annotation> ista::owl2::Axiom::annotations_
Referenced by addAnnotation, formatAnnotations, getAnnotations, hasAnnotations, setAnnotations.
virtual ista::owl2::Axiom::~Axiom()=default
virtual std::string ista::owl2::Axiom::toFunctionalSyntax() const =0
Convert to OWL2 Functional Syntax.
virtual std::string ista::owl2::Axiom::getAxiomType() const =0
Get the type of this axiom.
std::vector< Annotation > ista::owl2::Axiom::getAnnotations() const
Get annotations on this axiom.
References annotations_.
bool ista::owl2::Axiom::hasAnnotations() const
Check if this axiom has annotations.
References annotations_.
void ista::owl2::Axiom::addAnnotation(const Annotation &annotation)
Add an annotation to this axiom.
References annotations_.
void ista::owl2::Axiom::setAnnotations(const std::vector< Annotation > &annotations)
Set all annotations.
References annotations_.
std::string ista::owl2::Axiom::formatAnnotations() const
Helper to format annotations in functional syntax.
References annotations_.
Referenced by ista::owl2::AnnotationAssertion::toFunctionalSyntax, ista::owl2::AnnotationPropertyDomain::toFunctionalSyntax, ista::owl2::AnnotationPropertyRange::toFunctionalSyntax, ista::owl2::AsymmetricObjectProperty::toFunctionalSyntax, ista::owl2::ClassAssertion::toFunctionalSyntax, ista::owl2::DataPropertyAssertion::toFunctionalSyntax, ista::owl2::DataPropertyDomain::toFunctionalSyntax, ista::owl2::DataPropertyRange::toFunctionalSyntax, ista::owl2::DatatypeDefinition::toFunctionalSyntax, ista::owl2::Declaration::toFunctionalSyntax, ista::owl2::DifferentIndividuals::toFunctionalSyntax, ista::owl2::DisjointClasses::toFunctionalSyntax, ista::owl2::DisjointDataProperties::toFunctionalSyntax, ista::owl2::DisjointObjectProperties::toFunctionalSyntax, ista::owl2::DisjointUnion::toFunctionalSyntax, ista::owl2::EquivalentClasses::toFunctionalSyntax, ista::owl2::EquivalentDataProperties::toFunctionalSyntax, ista::owl2::EquivalentObjectProperties::toFunctionalSyntax, ista::owl2::FunctionalDataProperty::toFunctionalSyntax, ista::owl2::FunctionalObjectProperty::toFunctionalSyntax, ista::owl2::HasKey::toFunctionalSyntax, ista::owl2::InverseFunctionalObjectProperty::toFunctionalSyntax, ista::owl2::InverseObjectProperties::toFunctionalSyntax, ista::owl2::IrreflexiveObjectProperty::toFunctionalSyntax, ista::owl2::NegativeDataPropertyAssertion::toFunctionalSyntax, ista::owl2::NegativeObjectPropertyAssertion::toFunctionalSyntax, ista::owl2::ObjectPropertyAssertion::toFunctionalSyntax, ista::owl2::ObjectPropertyDomain::toFunctionalSyntax, ista::owl2::ObjectPropertyRange::toFunctionalSyntax, ista::owl2::ReflexiveObjectProperty::toFunctionalSyntax, ista::owl2::SameIndividual::toFunctionalSyntax, ista::owl2::SubAnnotationPropertyOf::toFunctionalSyntax, ista::owl2::SubClassOf::toFunctionalSyntax, ista::owl2::SubDataPropertyOf::toFunctionalSyntax, ista::owl2::SubObjectPropertyOf::toFunctionalSyntax, ista::owl2::SymmetricObjectProperty::toFunctionalSyntax, ista::owl2::TransitiveObjectProperty::toFunctionalSyntax.