ista::owl2::loader::TransformEngine
using ista::owl2::loader::TransformEngine::TransformFunc = std::function<std::string(const std::string&, const std::map<std::string, std::string>&)>
std::map<std::string, TransformFunc> ista::owl2::loader::TransformEngine::builtins_
ista::owl2::loader::TransformEngine::TransformEngine()
Construct a TransformEngine with built-in transforms registered.
std::string ista::owl2::loader::TransformEngine::apply(const std::string &transform_name, const std::string &value, const std::map< std::string, TransformDef > &registry) const
Apply a named transform from the registry.
transform_name Name of the transform to apply value The input value to transform registry Map of transform names to definitions Transformed value TransformException if transform not found or fails
References apply_def.
Referenced by apply_def.
std::string ista::owl2::loader::TransformEngine::apply_def(const TransformDef &def, const std::string &value, const std::map< std::string, TransformDef > &registry) const
Apply a transform definition directly.
def The transform definition value The input value to transform registry Map of transform names (for resolving references in chains) Transformed value
References apply, apply_builtin, apply_def, ista::owl2::loader::TransformDef::params, ista::owl2::loader::TransformDef::steps, ista::owl2::loader::TransformDef::type.
Referenced by apply, apply_def.
std::string ista::owl2::loader::TransformEngine::apply_builtin(const std::string &type, const std::string &value, const std::map< std::string, std::string > &params) const
Apply a built-in transform by type name.
type The transform type (e.g., "split", "lowercase") value The input value params Transform parameters Transformed value TransformException if transform type unknown or fails
Referenced by apply_def.
void ista::owl2::loader::TransformEngine::register_builtin(const std::string &name, TransformFunc func)
Register a custom transform function.
name Transform type name func The transform function
bool ista::owl2::loader::TransformEngine::has_builtin(const std::string &name) const
Check if a builtin transform type exists.
std::vector< std::string > ista::owl2::loader::TransformEngine::get_builtin_names() const
Get list of available builtin transform types.
void ista::owl2::loader::TransformEngine::init_builtins()
std::string ista::owl2::loader::TransformEngine::get_param(const std::map< std::string, std::string > &params, const std::string &name, const std::string &default_value="") const
int ista::owl2::loader::TransformEngine::get_int_param(const std::map< std::string, std::string > &params, const std::string &name, int default_value=0) const