ista::owl2::loader::YamlNode
Type
using ista::owl2::loader::YamlNode::ScalarValue = std::string
using ista::owl2::loader::YamlNode::MapValue = std::map<std::string, YamlNodePtr>
using ista::owl2::loader::YamlNode::ListValue = std::vector<YamlNodePtr>
Type ista::owl2::loader::YamlNode::type_
ScalarValue ista::owl2::loader::YamlNode::scalar_
MapValue ista::owl2::loader::YamlNode::map_
ListValue ista::owl2::loader::YamlNode::list_
ista::owl2::loader::YamlNode::YamlNode()
ista::owl2::loader::YamlNode::YamlNode(const std::string &scalar)
ista::owl2::loader::YamlNode::YamlNode(const MapValue &map)
ista::owl2::loader::YamlNode::YamlNode(const ListValue &list)
Type ista::owl2::loader::YamlNode::type() const
bool ista::owl2::loader::YamlNode::is_null() const
References Null.
bool ista::owl2::loader::YamlNode::is_scalar() const
References Scalar.
bool ista::owl2::loader::YamlNode::is_map() const
References Map.
bool ista::owl2::loader::YamlNode::is_list() const
References List.
const std::string & ista::owl2::loader::YamlNode::as_string() const
References Scalar.
Referenced by as_bool, as_double, as_int.
int ista::owl2::loader::YamlNode::as_int() const
References as_string.
double ista::owl2::loader::YamlNode::as_double() const
References as_string.
bool ista::owl2::loader::YamlNode::as_bool() const
References as_string.
const YamlNode::MapValue & ista::owl2::loader::YamlNode::as_map() const
References Map.
bool ista::owl2::loader::YamlNode::has_key(const std::string &key) const
References Map.
Referenced by get_bool, get_int, get_string.
YamlNodePtr ista::owl2::loader::YamlNode::get(const std::string &key) const
References make_null, Map.
Referenced by get_bool, get_int, get_string, operator[], operator[].
YamlNodePtr ista::owl2::loader::YamlNode::operator[](const std::string &key) const
References get.
const YamlNode::ListValue & ista::owl2::loader::YamlNode::as_list() const
References List.
size_t ista::owl2::loader::YamlNode::size() const
References List, Map.
YamlNodePtr ista::owl2::loader::YamlNode::get(size_t index) const
References List, make_null.
YamlNodePtr ista::owl2::loader::YamlNode::operator[](size_t index) const
References get.
std::string ista::owl2::loader::YamlNode::get_string(const std::string &key, const std::string &default_value="") const
References get, has_key.
int ista::owl2::loader::YamlNode::get_int(const std::string &key, int default_value=0) const
References get, has_key.
bool ista::owl2::loader::YamlNode::get_bool(const std::string &key, bool default_value=false) const
References get, has_key.
void ista::owl2::loader::YamlNode::set(const std::string &key, YamlNodePtr value)
References Map.
void ista::owl2::loader::YamlNode::append(YamlNodePtr value)
References List.
static YamlNodePtr ista::owl2::loader::YamlNode::make_null()
Referenced by get, get, ista::owl2::loader::YamlParser::parse.
static YamlNodePtr ista::owl2::loader::YamlNode::make_scalar(const std::string &s)
static YamlNodePtr ista::owl2::loader::YamlNode::make_map()
static YamlNodePtr ista::owl2::loader::YamlNode::make_list()