ista::owl2::Annotation
AnnotationProperty ista::owl2::Annotation::property_
AnnotationValue ista::owl2::Annotation::value_
std::vector<Annotation> ista::owl2::Annotation::annotations_
ista::owl2::Annotation::Annotation(const AnnotationProperty &property, const AnnotationValue &value)
Construct an annotation with a property and value.
property The annotation property value The annotation value (IRI, Literal, or AnonymousIndividual)
Referenced by addAnnotation, operator!=, operator==.
ista::owl2::Annotation::Annotation(const AnnotationProperty &property, const AnnotationValue &value, const std::vector< Annotation > &annotations)
Construct an annotation with nested annotations.
property The annotation property value The annotation value annotations Nested annotations on this annotation
AnnotationProperty ista::owl2::Annotation::getProperty() const
Get the annotation property.
AnnotationValue ista::owl2::Annotation::getValue() const
Get the annotation value.
std::vector< Annotation > ista::owl2::Annotation::getAnnotations() const
Get nested annotations.
bool ista::owl2::Annotation::hasAnnotations() const
Check if this annotation has nested annotations.
void ista::owl2::Annotation::setProperty(const AnnotationProperty &property)
Set the annotation property.
void ista::owl2::Annotation::setValue(const AnnotationValue &value)
Set the annotation value.
void ista::owl2::Annotation::addAnnotation(const Annotation &annotation)
Add a nested annotation.
References Annotation.
std::string ista::owl2::Annotation::toFunctionalSyntax() const
Convert to OWL2 Functional Syntax.
References getValueAsString.
std::string ista::owl2::Annotation::getValueAsString() const
Get the value as a string representation.
Referenced by toFunctionalSyntax.
bool ista::owl2::Annotation::operator==(const Annotation &other) const
References Annotation.
bool ista::owl2::Annotation::operator!=(const Annotation &other) const
References Annotation.