ista::owl2::Entity
IRI ista::owl2::Entity::iri_
Referenced by Entity, getIRI, operator<, operator==.
ista::owl2::Entity::Entity(const IRI &iri)
References iri_.
Referenced by ista::owl2::AnnotationProperty::AnnotationProperty, ista::owl2::Class::Class, ista::owl2::DataProperty::DataProperty, ista::owl2::Datatype::Datatype, ista::owl2::NamedIndividual::NamedIndividual, ista::owl2::ObjectProperty::ObjectProperty, operator!=, operator<, operator==.
virtual ista::owl2::Entity::~Entity()=default
IRI ista::owl2::Entity::getIRI() const
References iri_.
Referenced by ista::owl2::Ontology::getClassAssertions, ista::owl2::Ontology::getDataPropertyAssertions, ista::owl2::Ontology::getDisjointClassesAxioms, ista::owl2::Ontology::getEquivalentClassesAxioms, ista::owl2::Ontology::getIndividualsOfClass, ista::owl2::Ontology::getNeighbors, ista::owl2::Ontology::getObjectPropertyAssertions, ista::owl2::Ontology::getSubClassAxiomsForSubClass, ista::owl2::Ontology::getSubClassAxiomsForSuperClass, ista::owl2::Ontology::getSubDataPropertyAxioms, ista::owl2::Ontology::hasPath, std::hash< ista::owl2::AnnotationProperty >::operator(), std::hash< ista::owl2::Class >::operator(), std::hash< ista::owl2::DataProperty >::operator(), std::hash< ista::owl2::Datatype >::operator(), std::hash< ista::owl2::NamedIndividual >::operator(), std::hash< ista::owl2::ObjectProperty >::operator().
virtual std::string ista::owl2::Entity::getEntityType() const =0
bool ista::owl2::Entity::operator==(const Entity &other) const
References Entity, iri_.
bool ista::owl2::Entity::operator!=(const Entity &other) const
References Entity.
bool ista::owl2::Entity::operator<(const Entity &other) const
References Entity, iri_.