ista::owl2::Literal
std::string ista::owl2::Literal::lexical_form_
std::optional<IRI> ista::owl2::Literal::datatype_
std::optional<std::string> ista::owl2::Literal::language_tag_
ista::owl2::Literal::Literal(const std::string &lexical_form, const std::optional< std::string > &language_tag=std::nullopt)
Construct a plain literal with optional language tag.
lexical_form The string value language_tag Optional language tag (e.g., "en", "de")
Referenced by operator!=, operator<, operator==.
ista::owl2::Literal::Literal(const std::string &lexical_form, const IRI &datatype)
Construct a typed literal.
lexical_form The string value datatype IRI of the datatype
std::string ista::owl2::Literal::getLexicalForm() const
Get the lexical form (string representation).
std::optional< IRI > ista::owl2::Literal::getDatatype() const
Get the datatype IRI.
std::optional< std::string > ista::owl2::Literal::getLanguageTag() const
Get the language tag.
bool ista::owl2::Literal::isTyped() const
Check if this is a typed literal.
bool ista::owl2::Literal::hasLanguageTag() const
Check if this has a language tag.
std::string ista::owl2::Literal::toString() const
Convert to string representation.
bool ista::owl2::Literal::operator==(const Literal &other) const
References Literal.
bool ista::owl2::Literal::operator!=(const Literal &other) const
References Literal.
bool ista::owl2::Literal::operator<(const Literal &other) const
References Literal.