ista::owl2::IRI
std::string ista::owl2::IRI::full_iri_
std::string ista::owl2::IRI::namespace_uri_
std::optional<std::string> ista::owl2::IRI::prefix_
std::optional<std::string> ista::owl2::IRI::local_name_
ista::owl2::IRI::IRI(const std::string &iri_string)
Construct IRI from full IRI string.
iri_string Full IRI (e.g., "http://example.org/ontology#Class1")
Referenced by operator!=, operator<, operator==.
ista::owl2::IRI::IRI(const std::string &prefix, const std::string &local_name, const std::string &namespace_uri)
Construct IRI from prefix and local name.
prefix Namespace prefix (e.g., "ex") local_name Local name within namespace (e.g., "Class1") namespace_uri Full namespace URI (e.g., "http://example.org/ontology#")
std::string ista::owl2::IRI::getFullIRI() const
Get the full IRI string.
Full IRI
Referenced by std::hash< ista::owl2::IRI >::operator().
std::optional< std::string > ista::owl2::IRI::getPrefix() const
Get the namespace prefix (if available).
Optional prefix
std::optional< std::string > ista::owl2::IRI::getLocalName() const
Get the local name (if available).
Optional local name
Referenced by ista::owl2::CSVParser::parse_node_type.
std::string ista::owl2::IRI::getNamespace() const
Get the namespace URI.
Namespace URI
std::string ista::owl2::IRI::getAbbreviated() const
Get abbreviated form (prefix:localName) if available.
Abbreviated IRI or full IRI if no abbreviation exists
bool ista::owl2::IRI::isAbbreviated() const
Check if this IRI is abbreviated.
bool ista::owl2::IRI::operator==(const IRI &other) const
References IRI.
bool ista::owl2::IRI::operator!=(const IRI &other) const
References IRI.
bool ista::owl2::IRI::operator<(const IRI &other) const
References IRI.
std::string ista::owl2::IRI::toString() const
Convert to string (returns full IRI).
Referenced by ista::owl2::reasoner::KoncludeWrapper::check_satisfiability.