ista::owl2::OntologyFilter
std::shared_ptr<const Ontology> ista::owl2::OntologyFilter::ontology_
FilterCriteria ista::owl2::OntologyFilter::criteria_
ista::owl2::OntologyFilter::OntologyFilter(const Ontology &ontology)
Construct a filter for the given ontology.
ontology The ontology to filter
Referenced by excludeIndividuals, includeClassHierarchy, includeDeclarations, includePropertyHierarchy, withClasses, withIndividuals, withMaxDepth.
ista::owl2::OntologyFilter::OntologyFilter(std::shared_ptr< const Ontology > ontology)
Construct a filter with shared ownership of ontology.
ontology Shared pointer to the ontology to filter
FilterResult ista::owl2::OntologyFilter::filterByIndividuals(const std::unordered_set< IRI > &iris) const
Extract a subgraph containing specific individuals.
Includes all axioms that reference the specified individuals, along with their class assertions and property assertions. iris Set of individual IRIs to include FilterResult containing the filtered ontology
FilterResult ista::owl2::OntologyFilter::filterByClasses(const std::unordered_set< IRI > &class_iris) const
Filter by class membership.
Includes all individuals that are instances of the specified classes (according to ClassAssertion axioms), along with their related axioms. class_iris Set of class IRIs FilterResult containing the filtered ontology
FilterResult ista::owl2::OntologyFilter::filterByProperty(const IRI &property, const Literal &value) const
Filter by property value.
Includes individuals that have the specified property with the given value. For DataPropertyAssertion axioms, matches against the literal value. For ObjectPropertyAssertion axioms, matches against the target individual's IRI. property The property IRI to filter by value The literal value to match FilterResult containing the filtered ontology
FilterResult ista::owl2::OntologyFilter::filterByObjectProperty(const IRI &property, const IRI &target) const
Filter by object property target.
Includes individuals that have the specified object property pointing to the given target individual. property The object property IRI target The target individual IRI FilterResult containing the filtered ontology
FilterResult ista::owl2::OntologyFilter::extractNeighborhood(const IRI &seed, int depth) const
Extract k-hop neighborhood around seed individual(s).
Uses BFS to traverse the ontology graph, following property assertions up to the specified depth. Depth 0 includes only the seed node(s). seed The seed individual IRI depth Maximum number of hops (property edges) to traverse FilterResult containing the neighborhood subgraph
References extractNeighborhood.
Referenced by extractNeighborhood.
FilterResult ista::owl2::OntologyFilter::extractNeighborhood(const std::unordered_set< IRI > &seeds, int depth) const
Extract k-hop neighborhood around multiple seed individuals.
seeds Set of seed individual IRIs depth Maximum number of hops to traverse FilterResult containing the neighborhood subgraph
FilterResult ista::owl2::OntologyFilter::extractPath(const IRI &start, const IRI &end) const
Extract path(s) between two individuals.
Uses BFS to find if a path exists between start and end individuals through property assertions. Includes all axioms on the shortest path(s). start Starting individual IRI end Target individual IRI FilterResult containing the path subgraph (empty if no path exists)
FilterResult ista::owl2::OntologyFilter::randomSample(size_t n, unsigned int seed=42) const
Random sampling of individuals.
Randomly selects n individuals and extracts their axioms. Useful for creating training/test splits or sampling large ontologies. n Number of individuals to sample seed Random seed for reproducibility FilterResult containing the sampled subgraph
FilterResult ista::owl2::OntologyFilter::applyFilter(const FilterCriteria &criteria) const
Apply custom filter criteria.
Provides maximum flexibility by allowing arbitrary filtering logic through the FilterCriteria struct. criteria The filter criteria to apply FilterResult containing the filtered ontology
References ista::owl2::FilterCriteria::custom_filter, ista::owl2::FilterCriteria::exclude_individuals, ista::owl2::FilterCriteria::include_classes, ista::owl2::FilterCriteria::include_individuals, ista::owl2::FilterCriteria::max_depth, ista::owl2::FilterCriteria::property_value_filters.
Referenced by execute.
OntologyFilter & ista::owl2::OntologyFilter::withIndividuals(const std::unordered_set< IRI > &iris)
Builder pattern: start building a filter.
Returns *this for method chaining.
References OntologyFilter.
OntologyFilter & ista::owl2::OntologyFilter::withClasses(const std::unordered_set< IRI > &class_iris)
References OntologyFilter.
OntologyFilter & ista::owl2::OntologyFilter::excludeIndividuals(const std::unordered_set< IRI > &iris)
References OntologyFilter.
OntologyFilter & ista::owl2::OntologyFilter::withMaxDepth(int depth)
References OntologyFilter.
OntologyFilter & ista::owl2::OntologyFilter::includeClassHierarchy(bool include)
References OntologyFilter.
OntologyFilter & ista::owl2::OntologyFilter::includePropertyHierarchy(bool include)
References OntologyFilter.
OntologyFilter & ista::owl2::OntologyFilter::includeDeclarations(bool include)
References OntologyFilter.
FilterResult ista::owl2::OntologyFilter::execute() const
Execute the built filter.
FilterResult containing the filtered ontology
References applyFilter.
Referenced by ista::owl2::Ontology::createSubgraph.
std::shared_ptr< const Ontology > ista::owl2::OntologyFilter::getOntology() const
Get the source ontology.
std::unordered_set< IRI > ista::owl2::OntologyFilter::getAllIndividuals() const
Get all individuals mentioned in the ontology.
std::unordered_set< IRI > ista::owl2::OntologyFilter::getIndividualsOfClass(const IRI &class_iri) const
Get individuals that are instances of a class.
std::unordered_map< IRI, std::unordered_set< IRI > > ista::owl2::OntologyFilter::buildAdjacencyList() const
Build adjacency list for graph traversal Returns map: individual IRI → set of connected individual IRIs.
std::unordered_set< IRI > ista::owl2::OntologyFilter::bfsTraversal(const std::unordered_set< IRI > &seeds, int depth, const std::unordered_map< IRI, std::unordered_set< IRI > > &adj_list) const
BFS traversal from seed nodes up to depth.
std::unordered_set< IRI > ista::owl2::OntologyFilter::findPath(const IRI &start, const IRI &end, const std::unordered_map< IRI, std::unordered_set< IRI > > &adj_list) const
BFS to find path between two nodes Returns set of all individuals on shortest path(s).
bool ista::owl2::OntologyFilter::axiomReferencesIndividuals(const AxiomPtr &axiom, const std::unordered_set< IRI > &individuals) const
Check if an axiom references any of the target individuals.
std::unordered_set< IRI > ista::owl2::OntologyFilter::extractIndividualsFromAxiom(const AxiomPtr &axiom) const
Extract IRIs of individuals mentioned in an axiom.
FilterResult ista::owl2::OntologyFilter::createFilteredOntology(const std::unordered_set< IRI > &individuals) const
Create filtered ontology from set of individuals Includes all axioms that reference these individuals.
void ista::owl2::OntologyFilter::addClassHierarchyAxioms(Ontology &target, const std::unordered_set< IRI > &class_iris) const
Add class hierarchy axioms for the given classes.
void ista::owl2::OntologyFilter::addPropertyHierarchyAxioms(Ontology &target, const std::unordered_set< IRI > &property_iris) const
Add property hierarchy axioms.
void ista::owl2::OntologyFilter::addDeclarations(Ontology &target, const std::unordered_set< IRI > &entity_iris) const
Add declarations for referenced entities.
void ista::owl2::OntologyFilter::copyMetadata(Ontology &target) const
Copy ontology metadata (IRI, version, prefixes, imports).