ista::owl2::Ontology
std::optional<IRI> ista::owl2::Ontology::ontology_iri_
std::optional<IRI> ista::owl2::Ontology::version_iri_
std::unordered_set<IRI> ista::owl2::Ontology::imports_
std::vector<Annotation> ista::owl2::Ontology::ontology_annotations_
std::unordered_map<std::string, std::string> ista::owl2::Ontology::prefix_to_namespace_
std::unordered_map<std::string, std::string> ista::owl2::Ontology::namespace_to_prefix_
std::vector<AxiomPtr> ista::owl2::Ontology::axioms_
ista::owl2::Ontology::Ontology()
ista::owl2::Ontology::Ontology(const IRI &ontology_iri)
ista::owl2::Ontology::Ontology(const IRI &ontology_iri, const IRI &version_iri)
ista::owl2::Ontology::~Ontology()=default
std::optional< IRI > ista::owl2::Ontology::getOntologyIRI() const
void ista::owl2::Ontology::setOntologyIRI(const IRI &iri)
std::optional< IRI > ista::owl2::Ontology::getVersionIRI() const
void ista::owl2::Ontology::setVersionIRI(const IRI &iri)
std::unordered_set< IRI > ista::owl2::Ontology::getImports() const
void ista::owl2::Ontology::addImport(const IRI &import_iri)
void ista::owl2::Ontology::removeImport(const IRI &import_iri)
bool ista::owl2::Ontology::hasImport(const IRI &import_iri) const
std::vector< Annotation > ista::owl2::Ontology::getOntologyAnnotations() const
void ista::owl2::Ontology::addOntologyAnnotation(const Annotation &annotation)
void ista::owl2::Ontology::setOntologyAnnotations(const std::vector< Annotation > &annotations)
void ista::owl2::Ontology::clearOntologyAnnotations()
void ista::owl2::Ontology::registerPrefix(const std::string &prefix, const std::string &namespace_uri)
Referenced by ista::owl2::RDFXMLParser::Parser::parse.
std::optional< std::string > ista::owl2::Ontology::getNamespaceForPrefix(const std::string &prefix) const
std::optional< std::string > ista::owl2::Ontology::getPrefixForNamespace(const std::string &namespace_uri) const
std::unordered_map< std::string, std::string > ista::owl2::Ontology::getPrefixMap() const
void ista::owl2::Ontology::removePrefix(const std::string &prefix)
void ista::owl2::Ontology::clearPrefixes()
bool ista::owl2::Ontology::addAxiom(const AxiomPtr &axiom)
Referenced by addClassAssertion, addDataPropertyAssertion, addObjectPropertyAssertion, createIndividual.
bool ista::owl2::Ontology::removeAxiom(const AxiomPtr &axiom)
bool ista::owl2::Ontology::containsAxiom(const AxiomPtr &axiom) const
std::vector< AxiomPtr > ista::owl2::Ontology::getAxioms() const
void ista::owl2::Ontology::clearAxioms()
std::vector< std::shared_ptr< Declaration > > ista::owl2::Ontology::getDeclarationAxioms() const
std::vector< AxiomPtr > ista::owl2::Ontology::getClassAxioms() const
std::vector< AxiomPtr > ista::owl2::Ontology::getObjectPropertyAxioms() const
std::vector< AxiomPtr > ista::owl2::Ontology::getDataPropertyAxioms() const
std::vector< AxiomPtr > ista::owl2::Ontology::getAssertionAxioms() const
std::vector< AxiomPtr > ista::owl2::Ontology::getAnnotationAxioms() const
std::vector< std::shared_ptr< SubClassOf > > ista::owl2::Ontology::getSubClassAxiomsForSubClass(const Class &cls) const
References ista::owl2::Entity::getIRI.
std::vector< std::shared_ptr< SubClassOf > > ista::owl2::Ontology::getSubClassAxiomsForSuperClass(const Class &cls) const
References ista::owl2::Entity::getIRI.
std::vector< std::shared_ptr< EquivalentClasses > > ista::owl2::Ontology::getEquivalentClassesAxioms(const Class &cls) const
References ista::owl2::Entity::getIRI.
std::vector< std::shared_ptr< DisjointClasses > > ista::owl2::Ontology::getDisjointClassesAxioms(const Class &cls) const
References ista::owl2::Entity::getIRI.
std::vector< std::shared_ptr< SubObjectPropertyOf > > ista::owl2::Ontology::getSubObjectPropertyAxioms(const ObjectProperty &property) const
std::vector< std::shared_ptr< SubDataPropertyOf > > ista::owl2::Ontology::getSubDataPropertyAxioms(const DataProperty &property) const
References ista::owl2::Entity::getIRI.
std::vector< std::shared_ptr< ClassAssertion > > ista::owl2::Ontology::getClassAssertions(const NamedIndividual &individual) const
References ista::owl2::Entity::getIRI.
std::vector< std::shared_ptr< ObjectPropertyAssertion > > ista::owl2::Ontology::getObjectPropertyAssertions(const NamedIndividual &individual) const
References ista::owl2::Entity::getIRI.
std::vector< std::shared_ptr< DataPropertyAssertion > > ista::owl2::Ontology::getDataPropertyAssertions(const NamedIndividual &individual) const
References ista::owl2::Entity::getIRI.
std::unordered_set< Class > ista::owl2::Ontology::getClasses() const
References ista::owl2::Declaration::CLASS.
Referenced by containsClass, getClassCount.
std::unordered_set< ObjectProperty > ista::owl2::Ontology::getObjectProperties() const
References ista::owl2::Declaration::OBJECT_PROPERTY.
Referenced by containsObjectProperty, getObjectPropertyCount.
std::unordered_set< DataProperty > ista::owl2::Ontology::getDataProperties() const
References ista::owl2::Declaration::DATA_PROPERTY.
Referenced by containsDataProperty, getDataPropertyCount.
std::unordered_set< AnnotationProperty > ista::owl2::Ontology::getAnnotationProperties() const
References ista::owl2::Declaration::ANNOTATION_PROPERTY.
Referenced by containsAnnotationProperty, getEntityCount, getStatistics.
std::unordered_set< NamedIndividual > ista::owl2::Ontology::getIndividuals() const
References ista::owl2::Declaration::NAMED_INDIVIDUAL.
Referenced by containsIndividual, getIndividualCount.
std::unordered_set< Datatype > ista::owl2::Ontology::getDatatypes() const
References ista::owl2::Declaration::DATATYPE.
Referenced by containsDatatype, getEntityCount, getStatistics.
bool ista::owl2::Ontology::containsClass(const Class &cls) const
References getClasses.
bool ista::owl2::Ontology::containsObjectProperty(const ObjectProperty &property) const
References getObjectProperties.
bool ista::owl2::Ontology::containsDataProperty(const DataProperty &property) const
References getDataProperties.
bool ista::owl2::Ontology::containsAnnotationProperty(const AnnotationProperty &property) const
References getAnnotationProperties.
bool ista::owl2::Ontology::containsIndividual(const NamedIndividual &individual) const
References getIndividuals.
bool ista::owl2::Ontology::containsDatatype(const Datatype &datatype) const
References getDatatypes.
size_t ista::owl2::Ontology::getAxiomCount() const
Referenced by getStatistics.
size_t ista::owl2::Ontology::getEntityCount() const
References getAnnotationProperties, getClassCount, getDataPropertyCount, getDatatypes, getIndividualCount, getObjectPropertyCount.
Referenced by getStatistics.
size_t ista::owl2::Ontology::getClassCount() const
References getClasses.
Referenced by getEntityCount, getStatistics.
size_t ista::owl2::Ontology::getObjectPropertyCount() const
References getObjectProperties.
Referenced by getEntityCount, getStatistics.
size_t ista::owl2::Ontology::getDataPropertyCount() const
References getDataProperties.
Referenced by getEntityCount, getStatistics.
size_t ista::owl2::Ontology::getIndividualCount() const
References getIndividuals.
Referenced by getEntityCount, getStatistics.
std::string ista::owl2::Ontology::getStatistics() const
References getAnnotationProperties, getAxiomCount, getClassCount, getDataPropertyCount, getDatatypes, getEntityCount, getIndividualCount, getObjectPropertyCount.
std::string ista::owl2::Ontology::toFunctionalSyntax() const
References toFunctionalSyntax.
Referenced by ista::owl2::FunctionalSyntaxSerializer::serialize, ista::owl2::FunctionalSyntaxSerializer::serialize, toFunctionalSyntax.
std::string ista::owl2::Ontology::toFunctionalSyntax(const std::string &indent) const
NamedIndividual ista::owl2::Ontology::createIndividual(const Class &cls, const IRI &individual_iri)
Create a new individual of the specified class.
This creates a NamedIndividual and adds a ClassAssertion axiom to the ontology. cls The class to instantiate individual_iri The IRI for the new individual The created NamedIndividual
References addAxiom, ista::owl2::Declaration::NAMED_INDIVIDUAL.
bool ista::owl2::Ontology::addDataPropertyAssertion(const NamedIndividual &individual, const DataProperty &property, const Literal &value)
Add a data property assertion.
Creates and adds a DataPropertyAssertion axiom. individual The subject individual property The data property value The literal value true if the axiom was added successfully
References addAxiom.
bool ista::owl2::Ontology::addObjectPropertyAssertion(const NamedIndividual &subject, const ObjectProperty &property, const NamedIndividual &object)
Add an object property assertion.
Creates and adds an ObjectPropertyAssertion axiom. subject The subject individual property The object property object The object individual true if the axiom was added successfully
References addAxiom.
bool ista::owl2::Ontology::addClassAssertion(const NamedIndividual &individual, const Class &cls)
Add a class assertion to an existing individual.
individual The individual cls The class to assert true if the axiom was added successfully
References addAxiom.
std::vector< NamedIndividual > ista::owl2::Ontology::searchByDataProperty(const DataProperty &property, const Literal &value) const
Search for individuals by data property value.
property The data property to search value The literal value to match Vector of individuals with matching data property assertions
std::vector< NamedIndividual > ista::owl2::Ontology::searchByObjectProperty(const ObjectProperty &property, const NamedIndividual &object) const
Search for individuals by object property value.
property The object property to search object The object individual to match Vector of subject individuals with matching object property assertions
std::vector< std::pair< NamedIndividual, NamedIndividual > > ista::owl2::Ontology::getObjectPropertyAssertions(const ObjectProperty &property) const
Get all object property assertions for a property.
property The object property Vector of (subject, object) pairs
std::vector< std::pair< NamedIndividual, Literal > > ista::owl2::Ontology::getDataPropertyAssertions(const DataProperty &property) const
Get all data property assertions for a property.
property The data property Vector of (subject, value) pairs
std::vector< Class > ista::owl2::Ontology::getClassesForIndividual(const NamedIndividual &individual) const
Get all classes that an individual is asserted to be an instance of.
individual The individual to query Vector of classes
bool ista::owl2::Ontology::isInstanceOf(const NamedIndividual &individual, const Class &cls) const
Check if an individual is an instance of a class.
individual The individual to check cls The class to check membership of true if there is a ClassAssertion axiom
bool ista::owl2::Ontology::isFunctionalObjectProperty(const ObjectProperty &property) const
Check if an object property is functional.
property The object property to check true if there is a FunctionalObjectProperty axiom
bool ista::owl2::Ontology::isFunctionalDataProperty(const DataProperty &property) const
Check if a data property is functional.
property The data property to check true if there is a FunctionalDataProperty axiom
std::shared_ptr< Ontology > ista::owl2::Ontology::createSubgraph(const class OntologyFilter &filter) const
Create a filtered subgraph using OntologyFilter.
filter The OntologyFilter to apply (must reference this ontology) Shared pointer to the filtered ontology
References ista::owl2::OntologyFilter::execute, ista::owl2::FilterResult::ontology.
std::unordered_set< NamedIndividual > ista::owl2::Ontology::getIndividualsOfClass(const Class &cls) const
Get all individuals that are instances of a class.
cls The class to query Set of individuals that have ClassAssertion axioms for this class
References ista::owl2::Entity::getIRI.
std::vector< NamedIndividual > ista::owl2::Ontology::getNeighbors(const NamedIndividual &individual, int depth=1) const
Get neighboring individuals within specified depth.
Uses BFS to traverse the ontology graph via object property assertions. individual The starting individual depth Maximum number of hops (default 1) Vector of individuals reachable within depth hops
References ista::owl2::Entity::getIRI.
bool ista::owl2::Ontology::hasPath(const NamedIndividual &from, const NamedIndividual &to) const
Check if a path exists between two individuals.
Uses BFS to determine reachability through object property assertions. from Starting individual to Target individual true if a path exists, false otherwise
References ista::owl2::Entity::getIRI.
void ista::owl2::Ontology::initializeStandardPrefixes()
bool ista::owl2::Ontology::isClassAxiom(const AxiomPtr &axiom) const
bool ista::owl2::Ontology::isObjectPropertyAxiom(const AxiomPtr &axiom) const
bool ista::owl2::Ontology::isDataPropertyAxiom(const AxiomPtr &axiom) const
bool ista::owl2::Ontology::isAssertionAxiom(const AxiomPtr &axiom) const
bool ista::owl2::Ontology::isAnnotationAxiom(const AxiomPtr &axiom) const