ista::owl2::loader::DatabaseReader
DataSourceDef ista::owl2::loader::DatabaseReader::source_
Referenced by build_query, ista::owl2::loader::MySqlReader::connect, ista::owl2::loader::SqliteReader::connect, connection_description, DatabaseReader.
std::vector<std::string> ista::owl2::loader::DatabaseReader::headers_
Referenced by close, headers, ista::owl2::loader::MySqlReader::next, ista::owl2::loader::PostgresReader::next, ista::owl2::loader::SqliteReader::next, open.
size_t ista::owl2::loader::DatabaseReader::total_rows_
Referenced by close, open, row_count.
bool ista::owl2::loader::DatabaseReader::is_connected_
Referenced by close, open.
bool ista::owl2::loader::DatabaseReader::query_executed_
Referenced by close, open.
ista::owl2::loader::DatabaseReader::DatabaseReader(const DataSourceDef &source)
Construct a database reader from a data source definition.
source The data source definition containing connection info
References source_.
Referenced by ista::owl2::loader::MySqlReader::MySqlReader, ista::owl2::loader::PostgresReader::PostgresReader, ista::owl2::loader::SqliteReader::SqliteReader.
virtual ista::owl2::loader::DatabaseReader::~DatabaseReader()=default
bool ista::owl2::loader::DatabaseReader::open() override
Open the data source.
true if successful
References connect, disconnect, execute_query, fetch_column_names, fetch_row_count, headers_, is_connected_, query_executed_, total_rows_.
void ista::owl2::loader::DatabaseReader::close() override
Close the data source.
References disconnect, headers_, is_connected_, query_executed_, total_rows_.
Referenced by ista::owl2::loader::MySqlReader::~MySqlReader, ista::owl2::loader::PostgresReader::~PostgresReader, ista::owl2::loader::SqliteReader::~SqliteReader.
std::vector< std::string > ista::owl2::loader::DatabaseReader::headers() const override
Get the column headers.
References headers_.
size_t ista::owl2::loader::DatabaseReader::row_count() const override
Get total row count (0 if unknown).
References total_rows_.
virtual bool ista::owl2::loader::DatabaseReader::connect()=0
Establish a connection to the database.
true if connection was successful
Referenced by open.
virtual void ista::owl2::loader::DatabaseReader::disconnect()=0
Close the database connection.
Referenced by close, open.
virtual bool ista::owl2::loader::DatabaseReader::execute_query()=0
Execute the query and prepare for iteration.
This should execute the SQL query (either from table or custom query) and prepare the result set for iteration via has_next()/next(). true if query execution was successful
Referenced by open.
virtual std::vector< std::string > ista::owl2::loader::DatabaseReader::fetch_column_names()=0
Get the column names from the result set.
Called after execute_query() to populate headers_. Vector of column names
Referenced by open.
virtual size_t ista::owl2::loader::DatabaseReader::fetch_row_count()=0
Get the row count from the result set.
Called after execute_query() to populate total_rows_. Return 0 if count is unknown or expensive to compute. Number of rows, or 0 if unknown
Referenced by open.
std::string ista::owl2::loader::DatabaseReader::build_query() const
Build the SQL query string.
If a custom query is provided, returns it directly. Otherwise, builds a SELECT * FROM table query. The SQL query to execute
References source_.
Referenced by ista::owl2::loader::MySqlReader::execute_query, ista::owl2::loader::PostgresReader::execute_query, ista::owl2::loader::SqliteReader::execute_query.
std::string ista::owl2::loader::DatabaseReader::connection_description() const
Get a safe description of the connection for error messages.
Returns connection details without exposing the password. Connection description string
References source_.
Referenced by ista::owl2::loader::MySqlReader::connect, ista::owl2::loader::PostgresReader::connect.