ista::owl2::loader::YamlParser
YamlNodePtr ista::owl2::loader::YamlParser::parse(const std::string &content)
Parse YAML string into a node tree.
References ista::owl2::loader::YamlNode::make_null.
Referenced by ista::owl2::loader::DataMappingSpec::parse, parse_file.
YamlNodePtr ista::owl2::loader::YamlParser::parse_file(const std::string &filepath)
Parse YAML file.
References parse.
Referenced by ista::owl2::loader::DataMappingSpec::load_from_file.
YamlNodePtr ista::owl2::loader::YamlParser::parse_value(ParseState &state, int base_indent)
YamlNodePtr ista::owl2::loader::YamlParser::parse_map(ParseState &state, int base_indent)
YamlNodePtr ista::owl2::loader::YamlParser::parse_list(ParseState &state, int base_indent)
YamlNodePtr ista::owl2::loader::YamlParser::parse_inline_map(ParseState &state)
YamlNodePtr ista::owl2::loader::YamlParser::parse_inline_list(ParseState &state)
std::string ista::owl2::loader::YamlParser::parse_scalar(ParseState &state)
std::string ista::owl2::loader::YamlParser::parse_key(ParseState &state)