ista::owl2
using ista::owl2::AnnotationValue = std::variant<IRI, Literal, AnonymousIndividual>
Represents an OWL2 annotation value.
An annotation value can be an IRI, a Literal, or an AnonymousIndividual.
using ista::owl2::AnnotationPtr = std::shared_ptr<Annotation>
using ista::owl2::AxiomPtr = std::shared_ptr<Axiom>
using ista::owl2::ObjectPropertyExpression = std::variant<ObjectProperty, std::pair<ObjectProperty, bool>>
Object property expression - can be a property or its inverse.
using ista::owl2::Individual = std::variant<NamedIndividual, AnonymousIndividual>
Individual - can be named or anonymous.
using ista::owl2::AnnotationSubject = std::variant<IRI, AnonymousIndividual>
Annotation subject - can be IRI or anonymous individual.
typedef std::shared_ptr< DataRange > ista::owl2::DataRangePtr = std::shared_ptr<DataRange>
using ista::owl2::ClassExpressionPtr = std::shared_ptr<ClassExpression>
using ista::owl2::ClassPtr = std::shared_ptr<Class>
using ista::owl2::DatatypePtr = std::shared_ptr<Datatype>
using ista::owl2::ObjectPropertyPtr = std::shared_ptr<ObjectProperty>
using ista::owl2::DataPropertyPtr = std::shared_ptr<DataProperty>
using ista::owl2::AnnotationPropertyPtr = std::shared_ptr<AnnotationProperty>
using ista::owl2::NamedIndividualPtr = std::shared_ptr<NamedIndividual>
using ista::owl2::AnonymousIndividualPtr = std::shared_ptr<AnonymousIndividual>
using ista::owl2::OntologyPtr = std::shared_ptr<Ontology>
Annotation ista::owl2::makeAnnotation(const AnnotationProperty &property, const IRI &value)
Helper function to create an annotation with an IRI value.
Annotation ista::owl2::makeAnnotation(const AnnotationProperty &property, const Literal &value)
Helper function to create an annotation with a Literal value.
Annotation ista::owl2::makeAnnotation(const AnnotationProperty &property, const AnonymousIndividual &value)
Helper function to create an annotation with an AnonymousIndividual value.
std::string ista::owl2::formatObjectPropertyExpression(const ObjectPropertyExpression &ope)
Format an object property expression in functional syntax.
Referenced by ista::owl2::AsymmetricObjectProperty::toFunctionalSyntax, ista::owl2::DisjointObjectProperties::toFunctionalSyntax, ista::owl2::EquivalentObjectProperties::toFunctionalSyntax, ista::owl2::FunctionalObjectProperty::toFunctionalSyntax, ista::owl2::HasKey::toFunctionalSyntax, ista::owl2::InverseFunctionalObjectProperty::toFunctionalSyntax, ista::owl2::InverseObjectProperties::toFunctionalSyntax, ista::owl2::IrreflexiveObjectProperty::toFunctionalSyntax, ista::owl2::NegativeObjectPropertyAssertion::toFunctionalSyntax, ista::owl2::ObjectPropertyAssertion::toFunctionalSyntax, ista::owl2::ObjectPropertyDomain::toFunctionalSyntax, ista::owl2::ObjectPropertyRange::toFunctionalSyntax, ista::owl2::ReflexiveObjectProperty::toFunctionalSyntax, ista::owl2::SubObjectPropertyOf::toFunctionalSyntax, ista::owl2::SymmetricObjectProperty::toFunctionalSyntax, ista::owl2::TransitiveObjectProperty::toFunctionalSyntax.
std::string ista::owl2::formatIndividual(const Individual &individual)
Format an individual in functional syntax.
Referenced by ista::owl2::ClassAssertion::toFunctionalSyntax, ista::owl2::DataPropertyAssertion::toFunctionalSyntax, ista::owl2::DifferentIndividuals::toFunctionalSyntax, ista::owl2::NegativeDataPropertyAssertion::toFunctionalSyntax, ista::owl2::NegativeObjectPropertyAssertion::toFunctionalSyntax, ista::owl2::ObjectPropertyAssertion::toFunctionalSyntax, ista::owl2::SameIndividual::toFunctionalSyntax.
std::string ista::owl2::formatAnnotationSubject(const AnnotationSubject &subject)
Format an annotation subject in functional syntax.
Referenced by ista::owl2::AnnotationAssertion::toFunctionalSyntax.
std::string ista::owl2::formatAnnotationValue(const AnnotationValue &value)
Format an annotation value in functional syntax.
Referenced by ista::owl2::AnnotationAssertion::toFunctionalSyntax.