ista::owl2::loader::LoadingStats
size_t ista::owl2::loader::LoadingStats::rows_processed
Referenced by merge, summary.
size_t ista::owl2::loader::LoadingStats::individuals_created
Referenced by merge, summary.
size_t ista::owl2::loader::LoadingStats::individuals_enriched
Referenced by merge, summary.
size_t ista::owl2::loader::LoadingStats::properties_added
Referenced by merge, summary.
size_t ista::owl2::loader::LoadingStats::relationships_created
Referenced by merge, summary.
size_t ista::owl2::loader::LoadingStats::rows_skipped
Referenced by merge, summary.
size_t ista::owl2::loader::LoadingStats::errors
Referenced by merge, summary.
std::vector<std::string> ista::owl2::loader::LoadingStats::error_messages
Referenced by merge.
void ista::owl2::loader::LoadingStats::merge(const LoadingStats &other)
References error_messages, errors, individuals_created, individuals_enriched, properties_added, relationships_created, rows_processed, rows_skipped.
Referenced by ista::owl2::loader::DataLoader::execute, ista::owl2::loader::DataLoader::execute_all_node_mappings, ista::owl2::loader::DataLoader::execute_all_relationship_mappings.
std::string ista::owl2::loader::LoadingStats::summary() const
References errors, individuals_created, individuals_enriched, properties_added, relationships_created, rows_processed, rows_skipped.